---
# tasks file for apache

    - name: Dodaję repozytorium DotDEB
      lineinfile:
        dest: /etc/apt/sources.list
        line: 'deb http://packages.dotdeb.org jessie all'

    - name: Dodaję źródła repozytorium DotDEB
      lineinfile:
        dest: /etc/apt/sources.list
        line: 'deb-src http://packages.dotdeb.org jessie all'

    - name: Pobieram klucz GPG dla repozytorium DotDEB
      command: wget https://www.dotdeb.org/dotdeb.gpg --no-check-certificate -N

    - name: Zatwierdzam klucz GPG dla repozytorium DotDEB
      command: apt-key add dotdeb.gpg

    - name: Przeprowadzam update APT
      command: apt update

    - name: Sprawdzam czy Apache2 jest zainstalowany w najnowszej wersji
      apt:
        name: apache2
        state: latest
        update_cache: yes
        cache_valid_time: 3600

    - name: Sprawdzam czy mod PHP7.0 do Apache2 jest zainstalowany w najnowszej wersji
      apt:
        name: libapache2-mod-php7.0
        state: latest
        update_cache: yes
        cache_valid_time: 3600

    - name: Instaluję wymagane moduły PHP7
      apt: name={{item}} state=latest update_cache=yes cache_valid_time=3600
      with_items:
       - php7.0
       - php7.0-bcmath
       - php7.0-cli
       - php7.0-common
       - php7.0-curl
       - php7.0-dev
       - php7.0-gd
       - php7.0-intl
       - php7.0-json
       - php7.0-ldap
       - php7.0-mbstring
       - php7.0-mcrypt
       - php7.0-mysql
       - php7.0-opcache
       - php7.0-readline
       - php7.0-soap
       - php7.0-xdebug
       - php7.0-xml

    - name: Hide ServerTokens
      lineinfile:
        dest: /etc/apache2/conf-enabled/security.conf
        regexp: '^ServerTokens'
        line: 'ServerTokens Prod'

    - name: Hide ServerSignature
      lineinfile:
        dest: /etc/apache2/conf-enabled/security.conf
        regexp: '^ServerSignature'
        line: 'ServerSignature Off'

    - name: Usuwam domyślny plik /var/www/html/index.html
      file:
        path: /var/www/html/index.html
        state: absent

    - name: Usuwam domyślny plik /var/www/html/index.nginx-debian.html
      file:
        path: /var/www/html/index.nginx-debian.html
        state: absent
    #- name: Disable index listing on default apache2 config
    #  replace:
    #    path: /etc/apache2/apache2.conf
    #    backup: yes
    #    after: '^<Directory \/var\/www\/>'
    #    regexp: '^Options.*'
    #    replace: 'Options FollowSymLinks'
    - name: Otwieram port TCP_IN 80, jeżeli jeszcze nie jest otwarty
      lineinfile:
        dest: /etc/csf/csf.allow
        regexp: '^tcp\|in\|d=80\|d={{ansible_default_ipv4.address}}'
        line: 'tcp|in|d=80|d={{ansible_default_ipv4.address}}'

    - name: Otwieram port TCP_OUT 80, jeżeli jeszcze nie jest otwarty
      lineinfile:
        dest: /etc/csf/csf.allow
        regexp: '^tcp\|out\|d=80\|s={{ansible_default_ipv4.address}}'
        line: 'tcp|out|d=80|s={{ansible_default_ipv4.address}}'

    - name: Restartuję CSF, aby zatwierdzić zmiany
      command: csf -r
