---
- name: Create groups
  group:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
    gid: "{{ item.gid | default(omit) }}"
    system: "{{ item.system | default(omit) }}"
  with_items: "{{ users_groups }}"
  when: item.state|default('present') != "absent"   # czemu to służy ?

- name: Create per-user groups
  group:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
    gid: "{{ item.gid | default(item.uid) | default(omit) }}"
    system: "{{ item.system | default(omit) }}"
  with_items: "{{ users }}"
  when: >   # Co oznacz znak >
    users_per_user_groups == true and
    item.state|default('present') != 'absent'

