# The default shell for a user if none is specified
users_default_shell: /bin/bash

# Create home dirs for new users? Set this to false if you manage home
# directories in some other way.
users_create_homedirs: yes

# Create groups for users with the same name as the users group
users_per_user_groups: yes

# If true, create a sudoers entry for the admin group allow root access.
users_manage_admin_sudoers: yes

# If true, assume the admin group is also used to run Ansible jobs. This
# disables requiretty for the admin group
users_admin_uses_ansible: yes

# If set to true, require a password for sudo, false to not require a password
users_admin_sudo_password: yes

users_admin_group: wheel
users_default_password: '!!'

# Lists of users to create and delete
users:
- name: kkochanski
  commnet: Kkochanski
  is_admin+: yes
  groups:
  - beancounters

users_groups:
- name: beancounters
- name: developers
  state: absent

#users_ssh_keys:
#- name: kkochanski
#  keys:
#  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCuR0YqwB/MjRvm262+1ygcyA16R0NQkpK3QxXWZgHjy8tUQLD114PO9l3/RT7aq/LnyOgjp8dvdM/cSR6RbfQbN3K2G/FGvpgFvVe91S1BxfSiqCqx7vhnV93hWIQmwjeBeZQDaLid+cimgfAcTh6mWBrqQrHeBqPdc/VqGXJvwOzcgBt6rqFuFRJ77YXa9CZJRxxPwlgVOwwJmVoC+GbqDXFayxhBNZQYiuhqzh8ucWY5aCPm+VjtRheGYUKkhLCRrlv/Y652+ekz2teJCj9dLoKJTgFg12IeNLOuHRWCBuX5oQsZs6SKqOz7ujAREJpB4W+rdbbEoIb7tXO5Po1F k0chan@k0chan-desktop